# ExeMode Config | Development by Exestudios (Copyright © 2025 ExeStudios aka Furios121 | All rights reserved)

#████████████████████████████████████████████
#█▄─▄▄─█▄─▀─▄█▄─▄▄─█▄─▀█▀─▄█─▄▄─█▄─▄▄▀█▄─▄▄─█
#██─▄█▀██▀─▀███─▄█▀██─█▄█─██─██─██─██─██─▄█▀█
#▀▄▄▄▄▄▀▄▄█▄▄▀▄▄▄▄▄▀▄▄▄▀▄▄▄▀▄▄▄▄▀▄▄▄▄▀▀▄▄▄▄▄▀

Config Version: 1.0.3

discord-webhook-url: "il-tuo-url-webhook-discord"