name: ExeMode
version: '1.0-SNAPSHOT-BETA'
main: org.Exestudios.exeMode.ExeMode
api-version: '1.21'
authors: [Exestudios]
description: A plugin for gamemode management

commands:
  exc:
    description: Switch to creative mode
    usage: /<command>
    permission: exemode.creative
  exa:
    description: Switch to adventure mode
    usage: /<command>
    permission: exemode.adventure
  exs:
    description: Switch to survival mode
    usage: /<command>
    permission: exemode.survival
  exsp:
    description: Switch to spectator mode
    usage: /<command>
    permission: exemode.spectator
  exe:
    description: Help command
    usage: /<command>
  exeban:
    description: ban a player from the server
    usage: /exban <giocatore> <motivo>
    permission: exemode.ban
    permission-message: "§c[ExeMode] Non hai il permesso di eseguire questo comando!"
    aliases: [eban, banplayer]
  exeunban:
    description: unaban a player from the server
    usage: /unexban <giocatore> <motivo>
    permission: exemode.unban
    permission-message: "§c[ExeMode] Non hai il permesso di eseguire questo comando!"
    aliases: [ eunban, unbanplayer ]
  exeupdate:
    description: Check for updates
    usage: /<command> [force]
    permission: exemode.update
  exekick:
    description: Espelle un giocatore dal server
    usage: /exekick <giocatore> <motivo>
    permission: exemode.kick
  exewarn:
    description: Warn a player
    usage: /exewarn <giocatore> <motivo>
    permission: exemode.warn
  exeunwarn:
    description: Unwarn a player
    usage: /exeunwarn <giocatore>
    permission: exemode.unwarn
  exesmg:
    description: Message a player
    usage: /<command> <giocatore> <messaggio>
    permission: exemode.smg
    permission-message: "§c[ExeMode] Non hai il permesso di eseguire questo comando!"
  exemute:
    description: Mute a player
    usage: /<command> <giocatore> <motivo>
    permission: exemode.mute
    permission-message: "§c[ExeMode] Non hai il permesso di eseguire questo comando!"
  exeunmute:
    description: Unmute a player
    usage: /<command> <giocatore>
    permission: exemode.unmute
    permission-message: "§c[ExeMode] Non hai il permesso di eseguire questo comando!"


permissions:
  exemode.creative:
    description: Allows using creative mode command
    default: op
  exemode.adventure:
    description: Allows using adventure mode command
    default: op
  exemode.survival:
    description: Allows using survival mode command
    default: op
  exemode.spectator:
    description: Allows using spectator mode command
    default: op
  exemode.update:
    description: Allows using update command
    default: op
  exemode.ban:
    description: Allows using ban command
    default: op
  exemode.unban:
    description: Allows using unban command
    default: op
  exemode.kick:
    description: Allows using kick command
    default: op
  exemode.warn:
    description: Allows using warn command
    default: op
  exemode.unwarn:
    description: Allows using unwarn command
    default: op
  exemode.smg:
    description: Allows using smg command
    default: op
  exemode.mute:
    description: Allows using mute command
    default: op
  exemode.unmute:
    description: Allows using unmute command
    default: op